### PR TITLE
pm2 as user

### PR DESCRIPTION
**Pull request by jarosser06**
* consolidated helper methods into lwrp
* added ability to run pm2 as a user
* added tests for change
* added home attr to pm2_application

### CODE REVIEW

**Comment by gdelvalle** [comment]
:+1:  .Not running a root would be a big win

**Comment by jarosser06** [comment]
Fixed

**Comment by miguelcnf** [comment]
Looks really good generally - just left a couple of comments inline.

Let me run kitchen and I'll merge it if it's good.

**Comment by jarosser06** [comment]
Thanks! I removed the pm2_config instance var, it should be good to go.

**Pull request merged**
